name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows:
      - Trivy
    types:
      - completed

jobs:
  build-and-push-image:
    uses: Mind-Hochschul-Netzwerk/.github/.github/workflows/ci.yaml@feature/common-workflow
    with:
      registry: ${{ vars.REGISTRY }}
      image_name: ${{ vars.IMAGE_NAME }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
