name: Trivy

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load environment variables
        run: |
          set -o allexport
          source .github/workflows/.env
          set +o allexport

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: os
          severity: CRITICAL,HIGH
